# Generated by Django 3.2.7 on 2021-09-19 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartparker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('transport_number', models.CharField(default=0, max_length=10)),
                ('description', models.TextField(max_length=450)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=50)),
                ('vehicle_no', models.CharField(max_length=8, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100)),
                ('phoneNumber', models.IntegerField(default=0)),
                ('reward_coins', models.IntegerField(default=0)),
                ('pincode', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='images.jpeg', upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlotsPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(default=' ', max_length=100)),
                ('slot_name', models.CharField(default=' ', max_length=100)),
                ('slot_available', models.BooleanField(default=True)),
                ('value', models.CharField(default='1', max_length=100)),
                ('edited', models.CharField(default='1', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='ReportImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, upload_to='ReportImages', verbose_name='report_images')),
                ('reportuser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='smartparker.report')),
            ],
        ),
        migrations.CreateModel(
            name='RentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(default=' ', max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('total_transport', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('money_per_hour', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('occupied_transport', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('latitude', models.CharField(blank=True, default=1, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, default=1, max_length=50, null=True)),
                ('hold', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, upload_to='RentImages', verbose_name='Image')),
                ('rentuser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='smartparker.rentregister')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(default=' ', max_length=100)),
                ('vehicle', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('amount_to_pay', models.PositiveIntegerField(blank=True, null=True)),
                ('booked', models.BooleanField(default=False)),
                ('booked_place', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_hours', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('booked_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ending_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
    ]
