# Generated by Django 3.2.7 on 2021-09-19 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartparker', '0003_alter_booking_booked_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartparker.rentregister'),
        ),
    ]
