# Generated by Django 3.2.7 on 2021-09-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartparker', '0004_alter_booking_booked_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentregister',
            name='total_money',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
